spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_todolist
    username: root
    password: 142536
    driver-class-name: com.mysql.cj.jdbc.Driver
